### ISSUE TITLE
Change WebUI Password via Docker YAML

### ISSUE THREAD

**Issue by spencerthayer** [linuxserver/docker-deluge#112]
Is it possible to preset the Deluge password, or disable the password, through the YAML? If not is it possible to make that happen?

**Comment by thelamer** [comment]
Unfortunately no it is not, the web.conf is created after startup and exists outside of deluge-console access. 
It is possible to manually hack in the sha1 and salt using a pythong script, but it is not something we would implement as not only do you need to have a custom script, but you need to somehow ensure deluge does not overwrite this change on shutdown.

**Comment by MyNameIsBorat** [comment]
How can i reset or change the password then?

**Comment by baldassarreFe** [comment]
I had a similar need and after much fiddling around this is my solution.

Context: I'm running this container in a docker compose with traefik. I want to enable https and change the webui password immediately, without first connecting to the webui via http and making those changes manually. The relevant parts of my docker compose look like this:
```yaml
services:

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik.yaml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"  # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS
      - "127.0.0.1:8080:8080"  # Dashboard local access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - ./traefik.yaml:/etc/traefik.yaml

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - deluge_config:/config
      - deluge_downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      # - 58846:58846 # Thin client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`deluge.local`)"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      - "traefik.http.services.deluge.loadbalancer.server.scheme=https"
```

After `docker compose up`, connecting to the webui at https://deluge.local will not work, because the traefik router tries to use HTTPS but the webui expects HTTP for now.

With the containers up, run these commands:
```bash
# Stop deluged and deluge-web before making changes (will create web.conf)
docker compose exec deluge s6-svc -d /run/service/svc-deluge-web
docker compose exec deluge s6-svc -d /run/service/svc-deluged
sleep 5

# Daemon: upload settings
docker compose exec deluge mv /config/core.conf /config/core.conf.bak
docker compose exec deluge cat /config/core.conf.bak |
  sed -E 's/"max_upload_slots_global": -?[0-9]+/"max_upload_slots_global": 2/' |
  sed -E 's/"max_upload_speed": -?[0-9]+(\.[0-9]+)?/"max_upload_speed": 50.0/' |
  docker compose exec --no-TTY deluge tee /config/core.conf
docker compose exec deluge chown --reference /config/core.conf.bak /config/core.conf
docker compose exec deluge chmod --reference /config/core.conf.bak /config/core.conf

# WebUI: enable HTTPS and change password
SALT='yoursalt'
PWD='yourpassword'
SHA1=$(python -c "
import hashlib
s = hashlib.sha1()
s.update('${SALT}'.encode('utf-8'))
s.update('${PWD}'.encode('utf-8'))
print(s.hexdigest())")
docker compose exec deluge mv /config/web.conf /config/web.conf.bak
docker compose exec deluge cat /config/web.conf.bak |
  sed -E 's/"https": false/"https": true/' |
  sed -E 's/"first_login": true/"first_login": false/' |
  sed -E "s/\"pwd_salt\": \"[0-9a-f]+\"/\"pwd_salt\": \"${SALT}\"/" |
  sed -E "s/\"pwd_sha1\": \"[0-9a-f]+\"/\"pwd_sha1\": \"${SHA1}\"/" |
  docker compose exec --no-TTY deluge tee /config/web.conf
docker compose exec deluge chown --reference /config/web.conf.bak /config/web.conf
docker compose exec deluge chmod --reference /config/web.conf.bak /config/web.conf

# Restart
docker compose exec deluge s6-svc -u /run/service/svc-deluged
docker compose exec deluge s6-svc -u /run/service/svc-deluge-web
```

Now the webui is served with https and with the new password.

Notes:
- The first this the container runs, `/config/core.conf` exists but `/config/web.conf` does not, boh
- Don't skip the `.bak` files because tee sometimes overwrites the output before it has been read in full, resulting in empty files
- I tried using `s6-svc -wD` and `s6-svc -wU` but they just hang without messages
- I'm sure the commands above can be added to a lightweight dockerfile on top of the base image, but for now I'm good

I hope it still helps 2 years later!
