### ISSUE TITLE
XMRig Crypto miner found running inside deluge docker container.

### ISSUE THREAD

**Issue by megamit** [linuxserver/docker-deluge#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
No crypto miners?

## Current Behavior
So i noticed all my cpu of my server was being eaten up by an xmrig process, choking an emby video i was watching.

```
top
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1946162 emby      20   0 1525024 477716  17000 R 323.5   2.9   4:17.56 ffmpeg
1813011 docker-+  20   0 3022804   2.3g   2552 S 250.8  14.7   8634:44 xmrig
```

Its from here i checked what was running in the deluge container and noticed a bunch of stuff i didnt expect to see
```
docker top deluge
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                1582417             1582394             0                   Mar27               ?                   00:00:00            s6-svscan -t0 /var/run/s6/services
root                1582516             1582417             0                   Mar27               ?                   00:00:00            s6-supervise s6-fdholderd
root                1582738             1582417             0                   Mar27               ?                   00:00:00            s6-supervise deluged
root                1582740             1582417             0                   Mar27               ?                   00:00:00            s6-supervise deluge-web
docker-+            1582742             1582738             10                  Mar27               ?                   12:14:02            /usr/bin/python3 /usr/bin/deluged -c /config -d --loglevel=info -l /config/deluged.log
docker-+            1582743             1582740             0                   Mar27               ?                   00:29:44            deluge-web
docker-+            1812993             1582742             0                   Mar30               ?                   00:00:00            /bin/bash /tmp/rshell2/rev.sh 8ca9d50ad55cc48635f2a66ac2edafd3414a89c2 rshell2.tar.gz /tmp/
docker-+            1813011             1812993             99                  Mar30               ?                   6-01:52:41          ./xmrig -B -l logfile
```

The ones that suck out to me are rshell2 and xmrig both of which i had never heard of till now.

xmrig turned out to be a crypto miner which explains where all my cpu was going.

rshell i cant find anything about online but im guessing its some kind of remote shell software.

## Environment
**OS:** Ubuntu 20.04.1
**CPU architecture:** x86_64
**How docker service was installed:**
Installed from apt package downloaded from docker website

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2"
services:
##  snip ...
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=210
      - PGID=999
      - UMASK_SET=<022>
      - TZ=Europe/London
    volumes:
      - /etc/docker-apps/deluge:/config
      - /media/extmedia/Videos/Unsorted:/data/Unsorted/
    ports:
      - 8112:8112
      - 58846:58846
    restart: unless-stopped
```
