### ISSUE TITLE
Unable to add/start torrents from Chrome browser?

### ISSUE THREAD

**Issue by Andoramb** [linuxserver/docker-deluge#122]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

0. Cleanup previous files / Fresh pull
1. Upload any torrent file /magnet link
2. Chrome/Brave: Impossible to change files location
3. Chrome/Brave: Impossible to start download
4. Microsoft Edge works fine.

## Environment
**OS:**  Ubuntu 21.04
**CPU architecture:** x86_64
**How docker service was installed:** According to the books :) Official docker script + following your description

## Command used to create docker container (run/create/compose/screenshot)

```
  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge
    restart: "no"
    ports:
      - 8453:8112
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Stockholm
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - "${HME}/deluge:/config"
      - "${MEDIA}:/downloads"
```
