### ISSUE TITLE
Not receiving any torrent data

### ISSUE THREAD

**Issue by Johnystar** [linuxserver/docker-deluge#126]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After adding and initialising a ``.torrent`` file or a magnet link it should start downloading the torrent files.

``ubuntu-21.04-desktop-amd64.iso`` downloads just fine on my desktop:
![image](https://user-images.githubusercontent.com/29976879/136670545-85d3b475-2032-44bc-9097-a75cbba76138.png)

## Current Behavior
Adding a ``.torrent`` file results in a tracker status of ``Error: Host not found (authoritative)`` and the magnet link doesn't even fill in any trackers. Both downloads report 0 seeds and peers, but the status is "Downloading" for both of them.

``.torrent`` (test ``ubuntu-21.04-desktop-amd64.iso`` download)
![image](https://user-images.githubusercontent.com/29976879/136670432-536b84c1-517a-4839-bb43-3dd07dd5b797.png)

magnet link (test ``archlinux-2021.10.01-x86_64.iso`` download)
![image](https://user-images.githubusercontent.com/29976879/136670489-3b15ca83-6762-4347-ba75-d05c30ec868f.png)

## Steps to Reproduce
1. deluge snippet from my ``docker-compose.yml`` file:
```
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /some/path/deluge-config:/config
      - /some/path/torrents:/downloads
    ports:
      - 8086:8112
      - 58846:58846
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```
2. **prefs/downloads** download to ``/downloads/downloading``
3. **prefs/downloads** move completed to ``/downloads/completed``
4. **prefs/network** disabled random incoming port and changed to ``6881``
5. (router) port-forwarded ``6881`` manually just to make sure

## Environment
**OS:** ``Debian GNU/Linux 11 (bullseye) x86_64``
**CPU architecture:** x86_64
**How docker service was installed:** Through official Docker APT repositories for Debian https://docs.docker.com/engine/install/debian/#install-using-the-repository

## Command used to create docker container (run/create/compose/screenshot)

``docker-compose up -d --build`` in the directory where my ``docker-compose.yml`` is located

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
Could you provide the magnet link and torrrent file you used please? I'll try it myself.

**Comment by Johnystar** [comment]
any luck? @j0nnymoe

**Comment by mpardalos** [comment]
I am having the same exact same issue. I have also tried switching to host networking and it does not fix this either, so it is probably not to do with port mappings.

```
 deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - /var/config/deluge:/config
      - /var/data/downloads:/downloads
    network_mode: "host"
```
