### ISSUE TITLE
WebUi stopped working since v2.0.4

### ISSUE THREAD

**Issue by ggogel** [linuxserver/docker-deluge#129]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

WebUi should work.

## Current Behavior

WebUi doesn't work. The issue appeared first with release `2.0.4-0202112121857ubuntu18.04.1-ls129`. Access through thin client and deluge-console works.

FireFox throws the following error in Debugger:
```
Uncaught ReferenceError: Deluge is not defined
    <anonymous> https://deluge.domain.me/:41
deluge.gogel.me:41:13
    <anonymous> https://deluge.domain.me/:41
```

## Steps to Reproduce

1. Open WebUi in any browser.
2. See an empty white page.

## Environment
**OS:** CentOS Stream
**CPU architecture:** x86_64
**How docker service was installed:** docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
deluge:
        volumes:
            - 'deluge:/config'
        restart: unless-stopped
        image: linuxserver/deluge:latest
```
