### ISSUE TITLE
Daemon doesn't start since rebase to Focal

### ISSUE THREAD

**Issue by peterrus** [linuxserver/docker-deluge#133]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Daemon should start

## Current Behavior
Daemon does not start, WebUI does start but can not connect to daemon (obviously). Daemon logs show:
```
unable to start deluged: [('SSL routines', 'SSL_CTX_use_certificate', 'ee key too small')
```
Web logs show:
```
Unable to connect to daemon, check host_id <redacted>
```

## Steps to Reproduce

1. Start container with `:2.0.5-0202112151848ubuntu20.04.1-ls136`
2. See that WebUI is unable to connect to daemon
3. Start container with previous release: `2.0.5-0202112151848ubuntu18.04.1-ls135`
4. Daemon starts again and WebUI is able to connect

## Environment
**OS:** Docker Host: Ubuntu 20.04 Focal
**CPU architecture:** x86_64
**How docker service was installed:**

Installed according to official Docker docs.

## Command used to create docker container (run/create/compose/screenshot)

```
deluge:
  # locked because of ssl bug (daemon cant start)
  image: linuxserver/deluge:2.0.5-0202112151848ubuntu18.04.1-ls135
  environment:  
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    - UMASK=022  # optional
    - DELUGE_LOGLEVEL=error  # optional
  volumes:
    - /opt/data/deluge:/config
    - some data volumes
  restart: unless-stopped
```
