### ISSUE TITLE
file_error_alert "not supported"

### ISSUE THREAD

**Issue by btowntkd** [linuxserver/docker-deluge#139]
I'm not sure exactly when this happened, but sometime a couple days ago, my deluge docker updated and my torrents all started failing.  I'm running Docker for Windows Desktop using WSL2. As soon as I add a torrent, it moved to "ERROR" state as soon as it receives any data whatsoever.

When I enable DEBUG logging, I see the following example error:
```
08:00:01 [DEBUG   ][deluge.core.alertmanager      :130 ] file_error_alert: slackware-14.2-iso file_open (/downloads/Incomplete/torrent/slackware-14.2-iso/slackware-14.2-install-dvd.iso) error: Not supported
08:00:01 [DEBUG   ][deluge.core.alertmanager      :135 ] Handling alert: file_error_alert
08:00:01 [DEBUG   ][deluge.core.alertmanager      :130 ] torrent_error_alert: slackware-14.2-iso ERROR: (95 Not supported) /downloads/Incomplete/torrent/slackware-14.2-iso/slackware-14.2-install-dvd.iso
08:00:01 [DEBUG   ][deluge.core.alertmanager      :130 ] torrent_paused_alert: slackware-14.2-iso paused
08:00:01 [DEBUG   ][deluge.core.alertmanager      :135 ] Handling alert: torrent_paused_alert
```

Any idea what might have changed, recently?

**Comment by delamoe** [comment]
I'm having the same issue, all torrents fail after a few seconds and the GUI shows them in an error state. Reverting to an older tag fixed for me. `deluge:amd64-2.0.5-0202202181752ubuntu20.04.1-ls140`
This is what the errors looked like:
```
deluge  | 16:04:42 [DEBUG][deluge.core.alertmanager:135 ] Handling alert: file_error_alert
deluge  | 16:04:42 [DEBUG][deluge.core.alertmanager:130 ] torrent_error_alert: <filename> ERROR: (19 No such device) /media/downloads/deluge/incomplete/<filename>
deluge  | 16:04:42 [DEBUG][deluge.core.alertmanager:130 ] file_error_alert: <filename> file_open (/media/downloads/deluge/incomplete/<filename>) error: No such device
```

**Comment by thelamer** [comment]
If you are using mergefs: 
https://github.com/linuxserver/docker-deluge/issues/140#issuecomment-1059799488

**Comment by btowntkd** [comment]
> If you are using mergefs: [#140 (comment)](https://github.com/linuxserver/docker-deluge/issues/140#issuecomment-1059799488)

The mount in question is an NTFS drive connected via Docker for WIndows Desktop + WSL2.  Following delamoe's suggestion of reverting to a previous tag also worked as a temporary fix for me.

**Comment by thelamer** [comment]
Can anyone having this issue do me a favor and try passing `--security-opt seccomp=unconfined` when running the latest container ?

**Comment by btowntkd** [comment]
It does not appear to change the problem.  For sanity's sake, this is my docker-compose with the suggested tweak:

```
deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    depends_on:
      - vpn
     security_opt:
       - seccomp:unconfined
    volumes:
      - ${APPDATA_PATH}/deluge:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
```
