### ISSUE TITLE
PUID and PGID both set to 0 not working as expected ?

### ISSUE THREAD

**Issue by thechile** [linuxserver/docker-deluge#14]
```
docker -v
Docker version 1.12.3, build 6b644ec

docker-compose -v
docker-compose version 1.8.1, build 878cff1
```

When i set the PUID and PGID to 0, the container doesn't get updated correctly. Below are some examples to illustrate. ( yes, running as root = naughty but curious why it doesn't work none the less )

with compose

```
 deluge:
    image: "linuxserver/deluge"
    environment:
      - "PUID=0"
      - "PGID=0"
```
I get wrong GID for abc within the container ? Remains as 1001. 

```
root@9e1274f0b92f:/$ egrep abc /etc/passwd /etc/group
/etc/passwd:abc:x:0:1001::/config:/bin/false
/etc/group:users:x:1000:games,abc
/etc/group:abc:!:1001:
```

But when i remove container, image and change the ENV within compose to some other random number.. 

```
 deluge:
    image: "linuxserver/deluge"
    environment:
      - "PUID=10"
      - "PGID=0"
```

It gives me what i'd expect ( i.e UID and GID as per ENV )

```
root@cd7e805d789d:/$ egrep abc /etc/passwd /etc/group
/etc/passwd:abc:x:10:0::/config:/bin/false
/etc/group:users:x:1000:games,abc
/etc/group:abc:!:0:
```

Any ideas ?

thanks.
