### ISSUE TITLE
deluge container keeps crashing within periods of less than 24 hours

### ISSUE THREAD

**Issue by panomitrius** [linuxserver/docker-deluge#141]
# I'm running the latest version of docker-deluge, and it keeps crashing within a periods of less than 24 hours

## Environment
**OS:** Ubuntu 20.04.4
**CPU architecture:** x86_64
**How docker service was installed:** Ubuntu package system

------- 

Before deluge crashes, everything works flawlessly. Sometimes there's an error message in the logs, and sometimes not (that's why I guess that error message might be irrelevant and not including it here). However, when I try to restart the container, docker gives the following error message:

`Error response from daemon: Cannot restart container deluge: No such container: d309ff71355087e23cc6a91b6e99a47a1a766a2c8c26f40197edd9aa07c2f6f9
`

I don't know what this container ID is referring to - the deluge container on my system currently has container ID 3ef7bbcaef50. In order to get deluge up and running again I have to delete the container and build a new one. I'm doing this with `docker-compose down; docker-compose up -d`. The next time it crashes, I get the same error message when trying to restart the container, but with a different non existing container id mentioned. (Before it crashes, there's no issue using `docker restart`).

I'm running deluge together with docker-compose and using as [gluetun VPN service](https://github.com/qdm12/gluetun) and connect the deluge container through that.

```
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    network_mode: service:gluetun
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './deluge-config:/config'
      - downloads.persistent:/downloads
    restart: always
```
