### ISSUE TITLE
MacOS Fuse NTFS mounted disk permission error

### ISSUE THREAD

**Issue by pfych** [linuxserver/docker-deluge#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Running docker compose on MacOS with `PUID` and `PGID` set correctly againts an NTFS mounted disk should not have permission errors.

I previously had this container running on a raspberry pi but upgraded to a Mac Mini, I simply took the drive from the pi and moved it to the Mac. Same config folder, downloads folder etc.

## Current Behavior
```sh
# Truncated output
chown: changing ownership for '/config [...]': Operation not permitted
chown: changing ownership for '/downloads [...]': Operation not permitted
```

## Steps to Reproduce

1. Set-up docker image on a linux machine and add a torrent, let it complete.
2. Move the drive to a machine running MacOS
3. Use MacFuse to mount the disk 
`sudo /usr/local/bin/ntfs-3g /dev/disk2s2 /Volumes/NTFS -o local -o allow_other -o auto_xattr -o auto_cache -o uid=501,gid=20` (issue still occurs without `-o uid=501,gid=20`)
4. Start docker container up with docker compose `PUID` and `GID` changed to new disk owner (Current MacOS user)
5. Container is unable to read any files

## Environment
**OS:** MacOS Catalina (10.15.7)
**CPU architecture:** x86_64
**How docker service was installed:** Docker Repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2"
services:
  openvpn-client:
    image: ghcr.io/wfg/openvpn-client
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN 
    environment:
      - KILL_SWITCH=on
      - FORWARDED_PORTS=12345
      - SUBNETS=192.168.0.0/24,192.168.1.0/24
    devices:
      - /dev/net/tun
    volumes:
      - /Volumes/NTFS/Docker/LinuxISOs/openvpn/config:/data/vpn
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    userns_mode: "host"
    depends_on:
      openvpn-client:
        condition: service_healthy
    environment:
      - PUID=501
      - PGID=20
      - TZ=Redacted/Redacted
      - DELUGE_LOGLEVEL=error
    volumes:
      - /Volumes/NTFS/Docker/LinuxISOs/Deluge:/config
      - /Volumes/NTFS/LinuxISOs:/downloads
    network_mode: container:openvpn-client
    restart: unless-stopped
```

User permissions:
```sh
user@Mac-mini LinuxISOs % id -u ${USER}
501
user@Mac-mini LinuxISOs % id -g ${USER}
20
```
```sh
user@Mac-mini LinuxISOs % ls -l /Volumes/NTFS/LinuxISOs
drwxrwxrwx@ 1 user  staff  106496 May 22 18:32 51 Added
drwxrwxrwx  1 user  staff   98304 May 22 18:51 52 Complete
```
I also tried adding `user: 501:20` to docker compose however it did not fix the issue.

## Docker logs

https://pastebin.com/YE3jb8xv, This is cut short since I stopped the container.
