### ISSUE TITLE
Can't open config files on Synology docker?

### ISSUE THREAD

**Issue by iogitio** [linuxserver/docker-deluge#40]
I'm getting a weird error. I've tried changing the UID/GID to match, even tried everything as root, still doesn't work. The issue is Deluge runs fine, but none of my settings are saved, at all. 

I get the following in the logs, but the odd thing is, the container creates the files in the /config and everything is there (all the files it says can't be opened are sitting there with full read/write permissions on every user).... stumped! :(

`

date | stream | content
-- | -- | --
2018-03-05 11:55:25 | stdout | [INFO    ] 03:55:25 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
2018-03-05 11:55:25 | stdout | [INFO    ] 03:55:25 server:666 Starting server in PID 227.
2018-03-05 11:55:24 | stdout | [WARNING ] 03:55:24 config:443 Unable to backup old config...
2018-03-05 11:55:24 | stdout | [WARNING ] 03:55:24 config:423 Unable to open config file: /config/hostlist.conf.1.2 because: [Errno 2] No such file or directory: '/config/hostlist.conf.1.2'
2018-03-05 11:55:24 | stdout | [WARNING ] 03:55:24 config:364 Unable to open config file /config/hostlist.conf.1.2: [Errno 2] No such file or directory: '/config/hostlist.conf.1.2'
2018-03-05 11:55:24 | stdout | [WARNING ] 03:55:24 config:364 Unable to open config file /config/web.conf: [Errno 2] No such file or directory: '/config/web.conf'
2018-03-05 11:55:23 | stdout | [INFO    ] 03:55:23 ui:127 Starting web ui..
2018-03-05 11:55:23 | stdout | [INFO    ] 03:55:23 ui:124 Deluge ui 1.3.15
2018-03-05 11:55:23 | stdout | [INFO    ] 03:55:23 configmanager:70 Setting config directory to: /config
2018-03-05 11:55:22 | stdout | [services.d] done.
2018-03-05 11:55:22 | stdout | [services.d] starting services
2018-03-05 11:55:22 | stdout | [cont-init.d] done.
2018-03-05 11:55:22 | stdout | [cont-init.d] 30-config: exited 0.
2018-03-05 11:55:22 | stdout | [cont-init.d] 30-config: executing...
2018-03-05 11:55:22 | stdout | [cont-init.d] 10-adduser: exited 0.
2018-03-05 11:55:22 | stdout |  
2018-03-05 11:55:22 | stdout | -------------------------------------
2018-03-05 11:55:22 | stdout | User gid:    911
2018-03-05 11:55:22 | stdout | User uid:    0
2018-03-05 11:55:22 | stdout |  
2018-03-05 11:55:22 | stdout | -------------------------------------
2018-03-05 11:55:22 | stdout | GID/UID
2018-03-05 11:55:22 | stdout | -------------------------------------
2018-03-05 11:55:22 | stdout | https://www.linuxserver.io/donations/
2018-03-05 11:55:22 | stdout | We gratefully accept donations at:
2018-03-05 11:55:22 | stdout | Brought to you by linuxserver.io
2018-03-05 11:55:22 | stdout |  
2018-03-05 11:55:22 | stdout |  
2018-03-05 11:55:22 | stdout | \|_\| \|___/ \|_\|  \__/
2018-03-05 11:55:22 | stdout | \| \| \__ \ \| \| \| () \|
2018-03-05 11:55:22 | stdout | \| \| / __\| \| \|  /  \
2018-03-05 11:55:22 | stdout | \| \|  ___   _    __
2018-03-05 11:55:22 | stdout | _         ()
2018-03-05 11:55:22 | stdout | -------------------------------------

`

**Comment by j0nnymoe** [comment]
Post your docker run command or whatever information you can provide about how you deploy the container please.

**Comment by cfcolaco** [comment]
Tried different PGID and GID, 
Tried mounting different dirs to /config
Curious fact is that if dir is empty, it creates some files but not all of them. 

```
drwxr-xr-x  4  911  911 4096 Feb  4 22:13 .
drwxr-xr-x 11 root root 4096 Feb  3 22:34 ..
-rw-r--r--  1  911  911   74 Feb  4 22:15 deluged.log
-rw-r--r--  1  911  911  168 Feb  4 22:13 hostlist.conf.1.2
drwxr-xr-x  2  911  911 4096 Feb  4 22:13 icons
drwxr-xr-x  2  911  911 4096 Feb  4 22:13 plugins
-rw-r--r--  1  911  911  556 Feb  4 22:12 web.conf
```
**Docker compose**

```
version: '3.3'

<...More Services ...>

  torrent:
    image: linuxserver/deluge
    networks:
      - rp
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58964:58946/udp"
    volumes:
      - /srv/PlexMedia/TVShows:/Downloads/TVShows
      - /srv/PlexMedia/Movies:/Downloads/Movies
      - /srv/docker-data/deluge:/config
    environment:
      - UMASK_SET=022
      - TZ=Europe/Stockholm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.torrent.port=8112"
        - "traefik.frontend.rule=Host:torrent.home"
        - "traefik.docker.network=homeswarm_rp"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.ContentTypeNoSniff=true" 
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.STSSeconds=15552000"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"

networks: 
  rp:
    attachable: true
    driver: overlay
```

Service logs:

```
root@docker01:~ # docker service logs homeswarm_torrent 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [s6-init] ensuring user provided files have correct perms...exited 0.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [fix-attrs.d] applying ownership & permissions fixes...
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [fix-attrs.d] done.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] executing container initialization scripts...
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] 10-adduser: executing... 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | usermod: no changes
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | -------------------------------------
homeswarm_torrent.1.uya1vcfa4t9v@docker02    |           _         ()
homeswarm_torrent.1.uya1vcfa4t9v@docker02    |          | |  ___   _    __
homeswarm_torrent.1.uya1vcfa4t9v@docker02    |          | | / __| | |  /  \ 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    |          | | \__ \ | | | () |
homeswarm_torrent.1.uya1vcfa4t9v@docker02    |          |_| |___/ |_|  \__/
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | Brought to you by linuxserver.io
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | We gratefully accept donations at:
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | https://www.linuxserver.io/donate/
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | -------------------------------------
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | GID/UID
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | -------------------------------------
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | User uid:    911
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | User gid:    911
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | -------------------------------------
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] 10-adduser: exited 0.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] 30-config: executing... 
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] 30-config: exited 0.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [cont-init.d] done.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [services.d] starting services
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [services.d] done.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [INFO    ] 23:13:05 configmanager:70 Setting config directory to: /config
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [INFO    ] 23:13:05 ui:124 Deluge ui 1.3.15
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [INFO    ] 23:13:05 ui:127 Starting web ui..
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [WARNING ] 23:13:07 config:364 Unable to open config file /config/hostlist.conf.1.2: [Errno 2] No such file or directory: '/config/hostlist.conf.1.2'
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [WARNING ] 23:13:07 config:423 Unable to open config file: /config/hostlist.conf.1.2 because: [Errno 2] No such file or directory: '/config/hostlist.conf.1.2'
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [WARNING ] 23:13:07 config:443 Unable to backup old config...
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [INFO    ] 23:13:07 server:666 Starting server in PID 213.
homeswarm_torrent.1.uya1vcfa4t9v@docker02    | [INFO    ] 23:13:07 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
```
**Trying to open deluge-console from the container**

```
root@docker02:/srv/docker-data # docker container exec -ti homeswarm_torrent.1.uya1vcfa4t9vqudkjrynxqwjm /bin/bash
root@16c23291f4ca:/# 
root@16c23291f4ca:/# 
root@16c23291f4ca:/# 
root@16c23291f4ca:/# deluge-console
Traceback (most recent call last):
  File "/usr/bin/deluge-console", line 11, in <module>
    load_entry_point('deluge==1.3.15', 'console_scripts', 'deluge-console')()
  File "/usr/lib/python2.7/dist-packages/deluge/ui/console/main.py", line 75, in start
    Console().start()
  File "/usr/lib/python2.7/dist-packages/deluge/ui/console/main.py", line 72, in start
    ConsoleUI(self.args)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/console/main.py", line 200, in __init__
    d = self.do_command(connect_cmd)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/console/main.py", line 346, in do_command
    self.write("{!error!}" + str(e))
  File "/usr/lib/python2.7/dist-packages/deluge/ui/console/main.py", line 290, in write
    self.screen.add_line(line, not self.batch_write)
AttributeError: 'ConsoleUI' object has no attribute 'screen'
```



Hope this gives you enough deitails @j0nnymoe

**Comment by sparklyballs** [comment]
@cfcolaco , you've plussed 1 on something that isn't related to your problem.

the log about not finding config files is something that is shown on the first run of the container only, (unless you don't mount the /config volume)

**Comment by sparklyballs** [comment]
to connect to the console use:- 

s6-setuidgid abc deluge-console -c /config/

**Comment by j0nnymoe** [comment]
Also in your docker compose file, you haven't stated a PUID or PGID.

**Comment by cfcolaco** [comment]
Hmm .. I am sorry if the issue is not the same then .. it seemed to me quite similar tough ... 
@j0nnymoe It doesn't matter if I give GPID or PUID the result is all the same ...

From the container, I can create files inside the /config dir 
all other swarm nodes can see the files and changes. 

However no i noticed the daemon seems not to be starting at all, as even from WebUI I cannot connect to the daemon...

I'll try to get some clues ... and open a new issue. 
I am sorry again for the +1 in the wrong place then. =/

**Comment by thelamer** [comment]
@cfcolaco what you are talking about is not possible, if you pass the GPID and PUID env variables the abc user (by default 911:911) will use those IDs and this logic will chown those folders to those ids as root: 
https://github.com/linuxserver/docker-deluge/blob/master/root/etc/cont-init.d/30-config

This happens when the container starts and there is no logic blocking it. 

You need those vars:
```
  torrent:
    image: linuxserver/deluge
    networks:
      - rp
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58964:58946/udp"
    volumes:
      - /srv/PlexMedia/TVShows:/Downloads/TVShows
      - /srv/PlexMedia/Movies:/Downloads/Movies
      - /srv/docker-data/deluge:/config
    environment:
      - UMASK_SET=022
      - TZ=Europe/Stockholm
      - PUID=1000 <<<<<< your ids here 
      - PGID=1000 <<<<<< your ids here 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.torrent.port=8112"
        - "traefik.frontend.rule=Host:torrent.home"
        - "traefik.docker.network=homeswarm_rp"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.ContentTypeNoSniff=true" 
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.STSSeconds=15552000"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"

networks: 
  rp:
    attachable: true
    driver: overlay
```
