### ISSUE TITLE
Question about the required host network

### ISSUE THREAD

**Issue by Maskime** [linuxserver/docker-deluge#52]
Hi,

This is not so much an issue as a question : Why is it required to be on "host" network ?
When running this image with docker-compose and the linuxserver/letsencrypt image, the provided configuration for deluge in the letsencrypt image does not work because the deluge image is not a member of the network created by docker-compose.
Is the host mode required only because of the port forwarding ? Or is there another reason to that ?

Best regards and thank you so much for the hard work.

**Comment by khalpin11** [comment]
https://github.com/linuxserver/docker-deluge/issues/52#issue-363943580

> Hi,
> 
> This is not so much an issue as a question : Why is it required to be on "host" network ?
> When running this image with docker-compose and the linuxserver/letsencrypt image, the provided configuration for deluge in the letsencrypt image does not work because the deluge image is not a member of the network created by docker-compose.
> Is the host mode required only because of the port forwarding ? Or is there another reason to that ?
> 
> Best regards and thank you so much for the hard work.

@Maskime Hey I use compose and the letsencrypt container but I just setup my deluge subdomain conf file like this. 

`server {
    listen 443 ssl;

    server_name deluge.khalpin11.win;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        proxy_pass http://192.168.1.5:8116;
    }
}
`

Where `http://192.168.1.5` is the ip of my docker host on my local network and `8116` is my deluge webui port

**Comment by Maskime** [comment]
Hey,

Thanks for the feedback.
In the end I left the deluge container on the `bridge` network adapter and I just added the required port forwarding, so `docker-compose` service looks like this in the end :
```
  deluge:
    image: linuxserver/deluge:136 #upper version of the image are broken at the moment
    container_name: deluge
    hostname: deluge
    restart: on-failure
    env_file:
      - env_files/common_envs.env # This is a file where I put the PGID, PUID and TZ env vars
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - "${VOLUME_DIR}/media/downloads:/downloads"
      - "${VOLUME_DIR}/deluge/config:/config"
```
And it works like a charm so far.
You can see how I ended up connecting everything together here : https://github.com/Maskime/media-server

Just for curiosity sake, did you find a way so that your deluge container always have the same IP address within the docker-compose subnet ?
