### ISSUE TITLE
umask errors and extract plugin not working after latest update

### ISSUE THREAD

**Issue by paulmorabito** [linuxserver/docker-deluge#75]
Hi,

I'm running the x86 image with latest tag on Docker 18.09.7 on Debian Buster. I've been using deluge via this image for many months but after the last update a couple of days ago I noticed the following:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    999
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
./run: line 5: umask: `<': invalid symbolic mode operator
./run: line 5: umask: `<': invalid symbolic mode operator
[services.d] done.
04:25:32 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'
```

Furthermore, in the deluge config directory a lot of .conf files have a .conf~ created. Also, the extractor plugin is no longer working. Even though, it's enabled, there is nothing in the logs relating to it other than the initial message "04:25:32 [INFO    ][deluge.pluginmanagerbase      :189 ] Plugin Extractor enabled...".

If I diff the extractor.conf and extractor.conf~ the differences seem only to be spacing and its similar for other files.

Any ideas would be really appreciated.

**Comment by aptalca** [comment]
Post the command you used to create the container

**Comment by paulmorabito** [comment]
I'm using docker compose. The compose file is:

```
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: always
    environment:
      - PUID=1000
      - PGID=999
      - UMASK_SET=<022>
      - TZ=${TZ}
    ports:
      - "8112:8112"
      - "58846:58846"
    volumes:
      - /media/persistent/deluge:/config
      - /media/scratch/deluge:/media/scratch/deluge
    networks:
      - default
```

I've just noticed it looks like extractor is possibly working (or was) when I reverted to the previous release. However, its putting the archives into the root download directory and not the archive directory. It must have been putting them into the downloaded file's directory (if it exists) for sonarr to grab it previously. 

In any case, extractor.conf is:

```
{
    "file": 1,
    "format": 1
}{
    "extract_path": "/media/scratch/deluge",
    "use_name_folder": false
}
```
