### ISSUE TITLE
Research why container won't bind to IP using `network_mode: host` #Bug? #Question

### ISSUE THREAD

**Issue by ldexterldesign** [linuxserver/docker-deluge#86]
Hi,

Hope you're well

Thanks for software

## Expected Behavior

Connect to web ui at http://localhost:8112/

## Current Behavior

Does not connect to web ui at http://localhost:8112/

## Steps to Reproduce

Your config didn't work for me. My config does.

(Docker newb but) specifically, I'm curious why we need `network_mode: host`?

## Environment
**OS:** macOS, 10.15.3 (19D76)
**CPU architecture:** x86_64     
**How docker service was installed:** homebrew?

## Command used to create docker container (run/create/compose/screenshot)

Your config:

```
version: "2"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /path/to/deluge/config:/config
      - /path/to/your/downloads:/downloads
    restart: unless-stopped
```

My config:

```
version: "2"
services:

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ~/Downloads/-config/deluge:/config
      - ~/Downloads/deluge:/data/deluge
    ports:
      - 8112:8112
    restart: unless-stopped
```

Hope to hear back

Cheers
