### ISSUE TITLE
Unable to Manually Add label to torrent/Magnet 

### ISSUE THREAD

**Issue by neuman1812** [linuxserver/docker-deluge#96]
## Expected Behavior
When I manually add a torrent I need to change the label to "Tv-Sonarr"  so my sonarr install can pick it up.

## Current Behavior
Currently unable to manually add label,  The only option is " No label"
![no label](https://user-images.githubusercontent.com/9267886/86192936-b3e59c00-bb18-11ea-9475-18130df049e7.png)

--Note:  When I connect Sonarr to deluge it was able to add the "tv-sonarr" label itself and any torrent added by sonarr gets the label.    Its only when I manually add the torrent to deluge that Im unable to set the label.

## Steps to Reproduce
Add torrent or magnent link via url
Attempt to manually add label

## Environment
Ubuntu 20.04
**CPU architecture:** x86_64
docker installed via apt- Repository (https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

```
## Docker Compose
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - UMASK_SET=022
      - TZ=America/New_York # timezone, defined in .env
    volumes:
      - /data/Torrents/:/data/Torrents # downloads folder

```

## Docker logs
Docker logs  Can be found here: https://hastebin.com/unupibomen.sql

This includes the first startup and config via docker compose.  Second run is automated startup.
